# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160718191935 on 2016-08-20 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('dept_id',)},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('emp_id',)},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ('emp_id',)},
        ),
    ]
