# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160718191935 on 2016-08-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20160825_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
