# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160718191935 on 2016-08-25 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20160825_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_id',
            new_name='dept',
        ),
    ]
