# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160718191935 on 2016-08-26 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20160825_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
