# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160718191935 on 2016-08-26 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20160826_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
