# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160718191935 on 2016-08-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20160830_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
