# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160718191935 on 2016-08-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20160830_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='employee.Department'),
        ),
    ]
